### ISSUE TITLE
[BUG] Формирование ссылки на проверку для любого IP

### ISSUE THREAD

**Issue by GenRockeR** [Security-Experts-Community/siem-monkey#11]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

В событиях очень часто появляются не белые IP, а из приватных сетей.

По моему бесполезно искать серые адреса в virustotal и т.п. Можно предварительно проверять аналогично макросу "Адрес принадлежит внешней сети"

filter External_Address(string $IP) {
    (
        maybe_ipv4($IP) != null
        and not in_subnet($IP, "127.0.0.0/8")
        and not in_subnet($IP, "10.0.0.0/8")
        and not in_subnet($IP, "172.16.0.0/12")
        and not in_subnet($IP, "192.168.0.0/16")
        and not in_subnet($IP, "100.64.0.0/10")
        and not in_subnet($IP, "169.254.0.0/16")
        and not in_subnet($IP, "224.0.0.0/4")
    )
    or 
    (
        maybe_ipv6($IP) != null
        and not in_subnet($IP, "fc00::/7")
    )
}

### Expected Behavior

Срабатывание механизма только для белых сетей и ip

### Environment

```markdown
- OS:
- VSCode:
- VSCode-XP:
```

**Comment by grikos** [comment]
Думаю, что стоит доработать текущее поведение таким образом:
- убрать из кода все жестко заданные сервисы проверки IP-адресов
- оставить возможность в параметрах плагина задавать настройки для необходимых сервисов
- предусмотреть в виде отдельного чекбокса необходимость для каждого сервиса быть доступным для "локальных" адресов

Для локальных адресов может быть востребована функция проверки по внутренней CMDB, например.
