### ISSUE TITLE
[BUG] Не сохраняется учетная запись после редактирования

### ISSUE THREAD

**Issue by gribanov-ia** [Security-Experts-Community/siem-monkey#7]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

Не сохраняется учетная запись после редактирования

### Expected Behavior

Сохранение учетной записи после редактирования

### Steps To Reproduce

Перейти в "сбор данных" -> "учетные записи".
Выбрать для редактирования любую учетную запись, либо создать новую.
После заполнения всех обязательных полей нажать кнопку "Сохранить", ничего не происходит (F12->network пусто), запись не сохраняется.

### Environment

```markdown
Windows 11
Chrome Версия 112.0.5615.86 (Официальная сборка), (64 бит)
```

**Comment by grikos** [comment]
@gribanov-ia Спасибо за баг. 
Действительно вчерашнее обновление было сделано неаккуратно и при подмене параметров запроса не проверяло наличие необходимых полей. 
Пока добавил грубую обработку ошибок, которая позволяет скрипту не падать в случае отсутствия в параметрах запроса поля filter.groupByOrder (это то поле, которое плагин пытается удалять, чтобы вернуть поведение сортировки к тому, которое было знакомо пользователям до версии R25.1.

Исправил в 
https://github.com/Security-Experts-Community/siem-monkey/commit/b80159f2f9dde9565b9c6cdaba063e7263e48c8b

**Comment by gribanov-ia** [comment]
Да, проблема ушла, учетные записи теперь корректно сохраняются! Спасибо!
